resblock: '1'
upsample_rates: [5,4,2,2,2]
upsample_kernel_sizes: [11,8,4,4,4]
upsample_initial_channel: 512
resblock_kernel_sizes: [3,7,11]
resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
num_embeddings: 501
embedding_dim: 128
model_in_dim: 336
embedder_dim: 256

seed: 1234
batch_size: 32
lr: 0.0002
num_workers: 32
adam_b1: 0.8
adam_b2: 0.99
lr_decay: 0.999
mel_hop_size: 160
num_mels: 80
num_freq: 1025
n_fft: 1024
hop_size: 160
win_size: 640

sampling_rate: 16000
fmin: 55.
fmax: 7500.
fmax_for_loss: null

log_steps: 200
summary_steps: 2000
save_steps: 10000
val_steps: 10000
val_sample_steps: 50

